name: Mirror Parabol to Docker Hub

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag (e.g. v10.14.0)'
        required: true
        
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      # 1) Grab the code
      - uses: actions/checkout@v3

      # 2) Install jq so we can parse package.json
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # 3) Read `engines.node` out of package.json
      - name: Determine Node version
        id: nodever
        run: |
          NODE_VERSION=$(jq -r '.engines.node | ltrimstr("^") | ltrimstr("~")' package.json)
          echo "NODE_VERSION=$NODE_VERSION" >> $GITHUB_ENV

      # 4) Set up multi‑arch Docker builder (you can remove platforms if you only care about linux/amd64)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 5) Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 6) Build & push with the right build‑arg
      - name: Build & Push Parabol UBI Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/images/parabol-ubi/dockerfiles/basic.dockerfile
          platforms: linux/amd64
          build-args: |
            _NODE_VERSION=${{ env.NODE_VERSION }}
          push: true
          tags: |
            lucrin/parabol:${{ github.event.inputs.tag }}
            lucrin/parabol:latest
